apiVersion: v2
name: simpleapplication3
description: Deploys a Next.js application using the standard Node.js Chart
version: 0.2.0
dependencies:
  - name: nginx-deployment
    version: 0.2.0
    repository: oci://acraksdemo.azurecr.io/helm
  - name: otel-dotnet-sidecar
    version: 0.2.0
    repository: oci://acraksdemo.azurecr.io/helm